### ISSUE TITLE
hide YouTube #shorts needs an update due to updated way of showing shorts in feeds

### ISSUE THREAD

**Issue by h3oCharles** [xvello/letsblockit#107]
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

instead of a length counter, there's now a YT shorts logo which prevents the filter from working
![image](https://user-images.githubusercontent.com/8020330/159969180-55366200-43de-4326-ba10-0e897e5108f6.png)

**Comment by xvello** [comment]
Thanks for reporting this @h3oCharles 

I worked on supporting this new layout in https://github.com/xvello/letsblockit/pull/94 but they might have changed the markup since. Could you please [force a refresh](https://letsblock.it/help/refresh-list) or your filters first, to make sure you have the latest version?

I am currently away from home and will be back next weekend. If a refresh does not help, you might want to check [comments on this reddit post](https://www.reddit.com/r/uBlockOrigin/comments/tg220d/filters_to_completely_remove_youtube_shorts_like/) for updated rules.

Please keep me uodated!

**Comment by h3oCharles** [comment]
i don't have "letsblock.it - My filters" in custom, I've been pasting all filter lists in "My filters"

**Comment by xvello** [comment]
Okay, please try copying the new version from https://letsblock.it/filters/youtube-shorts then, as I updated it recently for the redesign.

This is the use case I designed the account system for: if you use the custom list system, we can ship updated filters easily when websites are updated.

**Comment by h3oCharles** [comment]
that seems to work. description might need updating to indicate hiding vids with the shorts logo

**Comment by xvello** [comment]
Happy to know it's working!
I will close this issue, and update the description next week.
