### ISSUE TITLE
Block Mix

### ISSUE THREAD

**Issue by Gomido** [xvello/letsblockit#130]
### What website(s) would this filter apply to?

Youtube

### What content should be blocked?

Blocking those stupid mixes suggested by YouTube (screenshot 1). I have a filter for that, but it doesn't quite work as it should. He leaves blank (screenshot 2) spaces for mixes. It works only in English and Polish.

- Screen 1

![image](https://user-images.githubusercontent.com/33147683/164978893-4246fa27-ad7b-4a55-a64c-4fe4b6622cbd.png)

- Screen 2
![image](https://user-images.githubusercontent.com/33147683/164978969-ca927435-6950-4b49-9430-709a860e79a6.png)

### Did you write a custom uBlock filter already?

```
www.youtube.com##:xpath(//ytd-two-column-browse-results-renderer[starts-with(@page-subtype,"home")]//a[starts-with(@title,"Mix - ")]):nth-ancestor(7)
www.youtube.com##:xpath(//ytd-two-column-browse-results-renderer[starts-with(@page-subtype,"home")]//a[starts-with(@title,"YouTube Mix")]):nth-ancestor(7)
www.youtube.com##:xpath(//ytd-two-column-browse-results-renderer[starts-with(@page-subtype,"home")]//a[starts-with(@title,"Mój YouTube Mix")]):nth-ancestor(7)
www.youtube.com##:xpath(//ytd-two-column-browse-results-renderer[starts-with(@page-subtype,"home")]//a[starts-with(@title,"Mój Mix")]):nth-ancestor(7)
www.youtube.com##:xpath(//ytd-two-column-browse-results-renderer[starts-with(@page-subtype,"home")]//a[starts-with(@title,"My Mix")]):nth-ancestor(7)
youtube.com###dismissable[class*="video-renderer"]:has([id^="video-title"]:has-text(/Mix/i))
youtube.com##ytd-playlist-renderer:has-text(/^Mix/)
youtube.com##ytd-compact-radio-renderer:has-text(/^Mix/)
youtube.com###dismissable:has-text(/^Mix/)
youtube.com###dismissable.style-scope ytd-compact-radio-renderer:has-text(/^Mix/)
```

**Comment by xvello** [comment]
Could you please try the following filters:

```
www.youtube.com##ytd-browse ytd-rich-item-renderer:has(#video-title-link[href*="&start_radio=1"])
www.youtube.com##ytd-search ytd-radio-renderer
www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-compact-radio-renderer
www.youtube.com##ytd-player div.videowall-endscreen a[data-is-list=true]
```

They block mixes, respectively in:
- the homepage
- the search results
- the player sidebar recommendations
- the player endscreen

As for the layout issue, I'm afraid there is not much we can do here, and it happens with my other youtube filters. While the subscription page is a simple item list that the browser wraps into rows, the homepage code inserts `ytd-rich-grid-row` elements wrapping a set number of items. Someone decided not to trust the browser to do such a simple job but, because they are so well-paid, we can only assume they had good reasons, right?
